README.md
And update the broken link accordingly as well.
=> Update README to reference fibers instead of tasks

proposals/fibers/Explainer.md
Includes fixing up an apparent search-and-replace error, where the Web spec term "micro task" was erroneously replaced with "micro fiber" (also removed the space, as "microtask" is the conventional way of writing it).
=> A few more typo fixes in Explainer.md

README.md
The README erroneously said that the typed continuations proposal depends on the `tail call` proposal. At the time of writing, the typed continuations proposal depends on `function references` and `exception handling` proposals.
=> Fix dependencies of typed continuations.

proposals/bag-o-stacks/Explainer.md
`switch.call` becomes `stack.new_switch` because it is the composition of
`stack.new` (not yet documented) and `switch`.
Similarly, `switch.return` becomes `switch_retire` because it performs a switch
and retires the previous active stack. We use "retire" instead of "return"
because "return" is not really an accurate description of what is happening.
=> [BoS] Rename instructions

proposals/bag-o-stacks/Explainer.md
Including a new `stack.new` instruction. Also add new descriptions of the
semantics of each instruction and a section on potential future instructions we
might want to add.
=> [BoS] Add detailed typing rules for instructions

proposals/bag-o-stacks/Explainer.md
Stack types are contravariant in all their parameters, including the return
stack reference.
=> [BoS] Fix description of subtyping

proposals/bag-o-stacks/Explainer.md
We previously allowed `stack.new` to bind arguments to the newly allocated
stack. However, producers might just as well want to perform partial application
with any stack reference, not just with newly allocated stacks. To simplify the
typing and semantics of `stack.new` and allow partial application to be used
more broadly, remove all operands of `stack.new` and add a separate `stack.bind`
instruction to perform partial application.
Since `stack.new` no longer does partial application, the optimization
opportunity realizable by a combined `stack.new_switch` instruction over a
sequence of `(stack.new) (switch)` is much smaller than it was before. Since
`stack.new_switch` no longer has as much benefit, remove it from the proposed
instruction set.
Update the prose and examples to replace …
=> [BoS] Add `stack.bind` and remove `stack.new_switch`

proposals/stack-switching/Explainer.md
Use the tag results to constrain the result type of the target continuation rather than using the tag parameters.
=> [explainer] Use tag results in symmetric switch

proposals/stack-switching/Explainer.md
Simplify the explanation of the typing rules by abbreviating `C.types[$ct] = cont $ft; C.types[$ft] = [t1*] -> [t2*]` to just `C.types[$ct] = cont [t1*] -> [t2*]`. We can use an auxiliary function to implement the same abbreviation in the formal spec.
=> [explainer] Abbreviate away continuation function types

proposals/stack-switching/Explainer.md
This came up as a point of ambiguity in a recent discussion, with the other possible design being trapping when the search finds a handler with the correct tag but incorrect event kind.
=> [explainer] Note that handler search accounts for event kind

proposals/stack-switching/Explainer.md
When looking up a type on the context, expand it (using `~~`) into the
expected composite type instead of using equality (`=`). Also fix some
places where equality should have been used when looking up tags.
=> [explainer] Use type expansion rather than equality

proposals/stack-switching/Explainer.md
- Refactor the rules for handlers out so they do not need to be repeated for both `resume` and `resume_throw`.
- Fix the constraint on the tag type in `(on $e switch)` handlers to ensure the tag result type is equal to the continuation return type. The tag result type must be a subtype of the resume result type to ensure the switched-to continuation has a compatible type, and it must also be a supertype to ensure the return continuation has a correct type. If we wanted to provide more flexibility here, we could upper bound the switched-to continuation result type with the tag results and lower bound the return continuation result type with the tag parameters, but I can't think of any benefit to doing that.
- Fix the constraint on the return continuation result type in `switch`. We know …
=> [explainer] Fix constraints and refactor handlers

proposals/stack-switching/Explainer.md
This patch redefines the `switch` instruction such that it only takes a single immediate type (in addition to the tag).
Resolves #76.
=> Single type annotation on `switch`

proposals/stack-switching/Explainer.md, proposals/stack-switching/examples/scheduler1.wast, proposals/stack-switching/examples/scheduler2.wast
The third section of the explainer currently compares task scheduling using `resume`/`suspend` vs `switch` using two example modules, `$scheduler1`  and `$scheduler2`. The explainer only contains a skeleton of the actual code.
This PR adds `.wast` files containing full code for these modules and links to them in the explainer. The code is carefully written to follow the structure shown in the explainer.
The code already follows the syntax update coming in #81.
Based on earlier versions of the code created  by @dhil.
=> Add full code for $scheduler1 and $scheduler2 examples

proposals/stack-switching/Explainer.md
Reverts WebAssembly/stack-switching#85
Due to subsumption, the previous typing already allowed `switch` to take non-nullable continuation references. The typing rules for an instruction should give the single most general type for its inputs.
Also remove other unnecessary `null?` in instruction typings.
=> Revert "Allow cont ref to be non-null in switch"

proposals/continuations/Explainer.md
Fix the syntax of examples for the handlers to match what the reference interpreter accepts.
=> Fix syntax for handlers in Explainer.md

interpreter/script/run.ml
This patch fixes #92 such that the interpreter exits gracefully on an unhandled tag.
```bash
$ cat test.wast
(module
(type $f1 (func))
(type $c1 (cont $f1))
(tag $e)
(func $s (suspend $e))
(elem declare func $s)
(func (export "main")
(resume $c1 (cont.new $c1 (ref.func $s)))
)
)
$ ./wasm test.wast
test.wast:5.12-5.24: suspension error: unhandled tag
```
=> Gracefully exit on unhandled tag

proposals/stack-switching/Explainer.md
There is a small inconsistency between the reference implementation in #84 and the explainer. In the explainer we write that the type index `$ft` on `cont $ft` should be encoded as an `u32` in the binary format. However, the reference interpreter actually encodes it as `s33`, similarly to how concrete heap types are encoded.
I do not have a strong preference for either encoding, but I suppose one can argue that the `s33` approach is more forward compatible in the sense that we can encode additional metadata.
=> [Binary format] Encode continuation type index as an `s33`

interpreter/valid/valid.ml, test/core/run.py, test/core/stack-switching/cont.wast
The validation of `switch` was not working as intended when the "switcher" and "switchee" had different continuation type immediates.
The fix is to replace the current continuation from the argument list with the switched-to continuation. The previous thing happened to be working when the "switcher" and "switchee" used the same continuation type immediate.
I also noticed a bug in the testsuite runner. It has not been running the stack switching tests since commit https://github.com/WebAssembly/stack-switching/commit/70086b9093716c2ffc958eff06a8a3bb73b9a8a2. I have added the "stack-switching" subdirectory to the test script runner such that the tests are now being run again by `make test`.
Resolves #98.
=> Fix validation of `switch`.

interpreter/binary/decode.ml, interpreter/binary/encode.ml
This patch brings the encoding and decoding of tag imports in sync with the exception handling proposal (as it is integrated into WebAssembly/spec branch `wasm-3.0`).
Resolves #101.
=> Fix encoding and decoding of tag imports.

interpreter/text/parser.mly, test/core/stack-switching/cont.wast
This patch fixes problems with parsing the stack switching instructions when they appear in unfolded form.
CC @ahuoguo who reported the issue to me.
=> Parsing stack switching instructions in unfolded form.

interpreter/exec/eval.ml, interpreter/syntax/types.ml, test/core/stack-switching/cont.wast
This patch fixes a bug with the arity of the continuation reference
generated by a `switch` (aka the current continuation). Its arity was
mistakenly derived from the switch-tag's codomain. The arity of the
current continuation can be obtained at the `switch` point by
deconstructing the type annotation on it.
Fixes #103.
=> Fix arity of generated switcher continuations

interpreter/exec/eval.ml
This patch renames `Handle` to `Prompt` (differentiating it better from `Handler`).
=> Rename administrative instruction `Handle` to `Prompt`.

proposals/stack-switching/Explainer.md, proposals/stack-switching/examples/generator-extended.wast, proposals/stack-switching/examples/generator.wast, proposals/stack-switching/examples/scheduler2-throw.wast
This PR adds a new section to the explainer with two more examples,  showing instructions and concepts not present in the original examples in section 3.
More specifically, the new section has an extended version of the generator example, showing `cont.bind` and tags with result types. A variation of the scheduling demonstrates `cont.throw`.
I've also made some minor changes to the existing examples, to increase consistency between the text in the explainer and the `wast` files for the old and new examples.
=> Add further examples to explainer

interpreter/valid/valid.ml, test/core/tag.wast
This PR fixes the following MWE:
```wat
(module
(rec
(type (func (param (ref null 1))))
(type (cont 0))
)
(tag (type 0))
)
```
=> Fixed tags with recursive type definitions

test/core/stack-switching/cont.wast
In Binaryen at least this exercises a different code path (context: https://github.com/WebAssembly/binaryen/pull/7815)
=> Add test for resume_throw in the initial execution

test/core/stack-switching/cont.wast
This was not otherwise covered.
=> Add a test for function subtyping

proposals/stack-switching/Explainer.md
This patch populates the "Execution" section of the Explainer document with the reduction rules for stack switching.
Resolves #91.
=> Reduction semantics
